services:
  mongo:
    image: mongo
    ports:
     - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: nehaBoda
      MONGO_INITDB_ROOT_PASSWORD: ApnaGuitar1023
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://nehaBoda:ApnaGuitar1023@localhost:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: nehaBoda
      ME_CONFIG_BASICAUTH_PASSWORD: ApnaGuitar1023
    depends_on:
      - mongo
volumes:
  mongo_data: